# Generated by Django 4.1.7 on 2023-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
