# Generated by Django 4.1.7 on 2023-06-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartz', '0004_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], max_length=100)),
                ('engine_displacement', models.FloatField()),
                ('horse_power', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('suv', 'SUV'), ('minivan', 'Minivan'), ('pickup', 'Pickup')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='compatible_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autopartz.car'),
        ),
    ]
